import re
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.db import transaction

from app.models import Categoria, PresentacionProducto, Producto  # type: ignore

# Una línea = un producto (tal cual está en la lista de la distribuidora).
# (código, nombre de la categoría, líneas)
CATALOGO = [
    ("CBOT", "Cerveza botella, litro y 750", """
AGUILA
AGUILA 1 LT *13
AGUILA IMPERIAL
AGUILA 750
BACANA X 30
CLUB 850 *13
CLUB COL
CORONA RET
CLUB ROJA
COLA Y POLA X 30
POKER 1 LT x13
COSTEÑA
CLUB TRIGO
COSTEÑA 750 *16
POKER 750
LIGHT
POKER
LIGHT 1.000
LIGHT 750
ANDINA 750*16
TEKATE 750 X16
"""),
    ("CLAT", "Cerveza lata, sixpack y botella pequeña", """
AGUILA 269 x6
AGUILA LATA x6
AZTECA X6
BACANA LATA
BACANA 269
CLUB 473
CLUB TRIGO LT
BUDW LATA 269x6
BUDWISER BT 250x6
CLUB DORADA lata 330 x6
CLUB NEGRA lata x6
CLUB ROJA lata x6
COLA Y POLA 1,5LTS X6
COLA Y POLA 330 SIX
águila Zero lata
CORONA 330 bt x6
CORONA CERO X 24
CORONA LATA 269 x6
CORONA LATA 473
CORONITA 210 x6
COSTEÑA
KAWFFMAN
MODELO X SXP
Corona de Zero lata
LIGHT LATA 330X6
LIKES 300 X UND
MICHELOB 269 lata
Poker 473
POKER LATA 330X6
REDDS LATA
STELLA  Bt x6
STELLA LT SXP
AGUILA 473 X6
AGUILA 473 X6 Light
águila light 269
ANDINA LATA 310
ANDINA LATA 269
ANDINA LIGHT 269
ANDINA LIGHT BOTELLA
Heineken 0.0
ANDINA REFAJO LATA
ANDINA REFAJO 1.5
ANDINA X 30
HEINEKEN 269 lata
HEINEKEN 250 x 30
HEINEKEN 250 x 24
HEINEKEN 310 LATA
HEINEKEN 330 *24
CENTRAL 330*30
CENTRAL 330*LATA
SOL 330*24
SOL 250 X 24 BOT
SOL LATA 310
TEKATE 330 BOTELLA
TECATE LATA
MILLER LITE 250
TRES COR*24 310cc Rose Lata
TRES CORDILLERAS*24 300cc Rose
TRES CORDILLERAS*24 300cc
"""),
    ("AGUA", "Aguardiente", """
LIDER BOTELLA
LIDER GARRAFA
LIDER MEDIA
LIDER 750 PET
LIDER 2 LTS
LIDER QUARTO AZUL
LIDER ROJO BOTELLA
LIDER ROJO MEDIA
LIDER ROJO QUARTO
LIDER VERDE 2 LITROS
LIDER VERDE BOTELLA
LIDER VERDE MEDIA
LIDER BOTELLA PET VERDE
LIDER QUARTO VERDE
ONIX EDICION LIMITADA
ONIX SELLO NEGRO ENVEGECIDO
ONIX GARRAFA
ONIX BOTELLA 24ª
ONIX BOTELLA 24ª 375
ONIX BOTELLA 24ª PET
ONIX BOTELLA
ONIX MEDIA
ONIX 24 QUARTO
ONIX SIN AZÚCAR 750
ONIX SIN AZÚCAR 375
ONIX SIN AZÚCAR 175
ANTIOQUEÑO 750
ANTIOQUEÑO 375
ANTIOQUEÑO 750 VERDE
ANTIOQUEÑO 375 VERDE
AGUARDIENTE BLANCO
"""),
    ("RON", "Ron", """
RON BOYACA 5 AÑOS
RON BOYACA 8 AÑOS
RON BOYACA 12 AÑOS
RON BOYACA BOTELLA
RON  BOYACA MEDIA
RON BOYACÁ QUARTO
AMARILLO 750
AMARILLO 375
AMARILLO 1 LT TBK
AMARILLO GARRAFA
AMARILLO 1 LT BOT
RON CALDAS BOTELLA OSCURO
RON CALDAS 1.000
RON CALDAS BOTELLA
RON CALDAS MEDIA
RON CALDAS QUARTO
RON CALDAS 5 AÑOS BOTELLA
RON CALDAS 5 AÑOS MEDIA
RON CALDAS 8 AÑOS BOTELLA
RON CALDAS 8 AÑOS MEDIA
RON CALDAS BLANCA
RON CREMA
RON CALDAS 15 AÑOS
RON CALDAS LICOR 750
RON CALDAS LICOR 375
MOLENDERO
RON TROPICO
RON SANTERO X 750ML
"""),
    ("RONS", "Ron y ron saborizado", """
BACARDI LIMON X 750 ML
BACARDI LIMON X 375ML
BACARDI CARTA BLANCA X 980ML
BACARDI CARTA BLANCA X 750 ML
BACARDI CARTA BLANCA X 1750 ML
BACARDI AÑEJO
BACARDI MOJITO
BACARDI ZOMBIE
BACARDI BAHAMA
BACARDI MANDARINA
BACARDI X 200ML RON
"""),
    ("WHIS", "Whisky", """
WHISKY BUCHANANS X 1000 master
WHISKY BUCHANANS X 750 master
WHISKY BUCHANANS TWO SOULS X 750ML
WHISKY BUCHANANS 12 AÑOS X 1000ML
WHISKY BUCHANANS 12 AÑOS X 750ML
WHISKY BUCHANANS 12 AÑOS X 375ML
WHISKY BUCHANANS 12 AÑOS X 200ML
WHISKY OLD PAR X 1000ML
WHISKY OLD PAR X 750ML
WHISKY OLD PAR X 500ML
WHISKY JHONNIE WALKER DOBLE BLACK X 700ML
WHISKY JHONNIE WALKER BLACK X 1000ML
WHISKY JHONNIE WALKER BLACK X 700ML
WHISKY JHONNIE WALKER BLACK X 375ML
WHISKY JHONNIE WALKER RED X 1000ML
WHISKY JHONNIE WALKER RED X 700ML
WHISKY JHONNIE WALKER RED X 375ML
WHISKY JHONNIE WALKER RED X 200ML
WHISKY CHIVAS 13 AÑOS  X 1000ML
WHISKY CHIVAS EXTRA X 750ML
WHISKY  CHIVAS EXTRA VASOS
WHISKY CHIVAS EXTRA X 375ML
WHISKY CHIVAS 12 AÑOS X 1000ML
WHISKY CHIVAS 12 Años X 700ML
WHISKY CHIVAS 12 AÑOS X 375ML
WHISKY ROYAL CHOICE
CLAN MAGREGOR 750
CLAN MAGREGOR 375
THE GLENLIVET
DEWARS 12 AÑOS
WHISKY JACK DANIELS X 750ML HONEY
WHISKY JACK DANIELS X 750ML MNZ
WHISKY JACK DANIELS X 750ML N'7
WHISKY JACK DANIELS X 375ML
WHISKY JACK DANIELS X 200ML
WHISKY JACK DANIELS X 50ML
BALLANTINES X 1000ML
BALLANTINES X 700ML
BALLANTINES X 375ML
BALLANTINES X 200ML
WHISKY BLACK AND WHITE X 1000ML
WHISKY BLACK AND WHITE X 1500ML
WHISKY BLACK AND WHITE X 700ML
WHISKY BLACK AND WHITE X 375ML
WHISKY BLACK AND WHITE X 200ML
WHISKY SOMETHING SPECIAL X 1000ML
WHISKY SOMETHING SPECIAL X 700ML
WHISKY SOMETHING SPECIAL X 375ML
WHISKY SOMETHING SPECIAL X 200 ML
WHISKY PASSPORT X 1000ML
WHISKY PASSPORT X 700ML
WHISKY PASSPORT X 500ML
WHISKY PASSPORT X 200ML
WHISKY VAT 69
JOHN THOMAS X 750ML
JOHN THOMAS X 375ML
JOHN THOMAS AZUL X 375ML
JOHN THOMAS AZUL X 750 ML
JAMESON X 750 ML
JAMESON X 375 ML
SIR EDWARDS X 750ML
SIR EDWARS X 375 ML
WHISKY HARRY 700
WHISKY GRANS X 1.750
WHISKY GRANS X 1000
WHISKY GRANS X 700
WHISKY GRANS X 350
WHISKY GRANS X 200
WHISKY SINGLETON 12 AÑOS X 750ML
WHISKY GRANDS CAJA AZUL X 750ML
WHISKY GRANDS DUGGANS X 750ML
WHISKY HAWARD
WHISKY BLACK JAC 750
WHISKY BLACK JAC 375
WHISKY CASTLE HAUSE
"""),
    ("VODK", "Vodka", """
VODKA SMIRNOFF TAMARINDO X 750ML
VODKA SMIRNOFF LULO X 1000ML
VODKA SMIRNOFF LULO X 750ML
VODKA SMIRNOFF LULO X 375ML
VODKA ABSOLUT ORIGINAL X 700ML
VODKA ABSOLUT ORIGINAL X 375ML
VODKA ABSOLUT CITRON X 700ML
VODKA ABSOLUT MANDARIN X 700ML
VODKA TROPCAYA
VODKA STALINAYA X 700 ML
"""),
    ("TEQU", "Tequila", """
TEQUILA EL JIMADOR REP X 1000
TEQUILA EL JIMADOR X 750ML
TEQUILA EL JIMADOR X 750ML Cristalino
TEQUILA EL JIMADOR X 375ML
TEQUILA EL JIMADOR BLANCO
TEQUILA NEWTON 1 LT
TEQUILA NEWTON 1 LT REP
TEQUILA PUERTA NEGRA
TEQUILA DON JULIO Blanco
TEQUILA JOSE CUERVO REPOSADO X 750ML
TEQUILA JOSE CUERVO REPOSADO X 375ML
TEQUILA JOSE CUERVO AZUL X 750ML
TEQUILA 3 CABALLOS REPOSADO X 1000ML
TEQUILA 3 CABALLOS GOLD X 750ML
TEQUILA 3 CABALLOS GOLD X 375 ML
TEQUILA 3 CABALLOS GOLD X 1000
TEQUILA OLMECA REPOSADO X 1000ML
TEQUILA OLMECA REPOSADO X 750ML
TEQUILA OLMECA REPOSADO X 375ML
TEQUILA OLMECA PLATA X 750ML
TEQUILA OLMECA PLATA X 375ML
TEQUILA OLMECA DARK CHOCOLATE 700 ML
TEQUILA 1800 REPOSADO
TEQUILA PATRON AÑEJO X 700 ML
TEQUILA PATRON X 700 ML
TEQUILA ALTOS X 700 ML
"""),
    ("GINE", "Ginebra", """
GINEBRA BOSQUE DE INDIAS
GINEBRA LONDON 750
GINEBRA GORDON 750
GINEBRA STERLING
GINEBRA HAWARD
"""),
    ("BRAN", "Brandy", """
BRANDY DOMECO 750
BRANDY DOMECO 375
BRANDY DOMECO 250
BRANDY CINCO ESTRELLAS  X375
BRANDY CINCO ESTRELA X 700
BRANDY GRAJALES 375
BRANDY GRAJALES 750
BRANDY Gran Brindis 750
BRANDY Gran Brindis 375
"""),
    ("CREM", "Cremas y licores dulces", """
CREMA DE WHISKY BAILEYS X 1000 ML
CREMA DE WHISKY BAILEYS X 750 ML
CREMA DE WHISKY BAILEYS X 375 ML
CREMA DE WHISKY BAILEYS TIRAMISU
CREMA DE WHISKY COPACABANA X 750 ML
CREMA DE WHISKY CASTEL HAUSE X 750 ML
CREMA DE WHISKY BLACK JACK X 750 ML
CREMA DE WHISKY BLACK JACK X 375 ML
CREMA WHISKY CASTLE HOUSE 375
CREMA WHISKY SAVORS 750
CREMA WHISKY SAVORS 375
CREMA DE WHISKY  WHISLEYS 700
CREMA COLOMA
CREMA BRYMOR
CREMA EXCELSO
CREMA SURTILEGIO
PIÑA COLADA REAGEE X 750ML
PIÑA COLADA MAVI X 750ML
MANZANILLA PODEROSA X 750 ML
PIÑA COLADA ISLEÑA
PIÑA COLADA TAHITI
SABAJON
SABAJON APOLO
WHISKY JAGERMEISTER X MINI
WHISKY JAGERMEISTER X 375 ML
WHISKY JAGERMEISTER X 700 ML
"""),
    ("VINO", "Vinos", """
VINO GRAJALES WALTIER
VINO MOSCATO PASSITO
VINO EMBAJADOR
VINO CASILLERO DEL DIABLO X 750 ML
VINO CASILLERO DEL DIABLO X 375 ML
VINO DUBONET 375
VINO DUBONET 700
VINO MANI SHEWTIZ
VINO SECO FRONTERA X 750 ML
VINO GATO NEGRO X 750ML
VINO GATO NEGRO X 375ML
VINO GRAJALES SEMI SECO X 750 ML
VINO SANGRE DE BOI
VINO LIEBFRAUMILCH
VINO SANZON X 750 ML
VINO CARIÑOSO X 750 ML
VINO MOSCATEL 750 ML
VINO GRAN BRINDIS TINTO X 750 ML
VINO CINZANO 1000
VINO MOSCATEL DE MISA
VINO DULCE AMADOR TINTO X 750ML
VINO CLOSS
VINO LA FERIA
VINO TOCORNAL
VINO PAZZITO
VINO POLERO
VINO TRES MEDALLAS
VINO ROSALEDA
VINO LA MERCED
VINO CHILENO CATA TINTO 1 LITRO
VINO VIÑA MAIPO
VINO VIÑA PIÑA
VINO COVIER 700
VINO TINTO ARIZO CAJAS
"""),
    ("CHAM", "Champañas", """
CHAMPIN
CHAMPAÑA MAGESTIC X 750 ML
CHAMPAÑA GRAN BRINDIS X 750
CHAMPAÑA GRAN BRINDIS X 2600
CHAMPAÑA PETERLONGO
CHAMPAÑA PETERLONGO 2600
CHAMPAÑA CASANOVA
CHAMPAÑA ALEJANDRIA X 750 ML
CHAMPAÑA MONSERRATE 2600
CAMPAÑA FRIZZANTINO
CHAMPAÑA GRAN CELEBRACIÓN 2600
CHAMPAÑA GRAN CELEBRACIÓN 750
CHAMPAÑA PICCINI
CHAMPAÑA ALTEZA
CHAMPAÑA LAMBRUSCO
JP CHENET X 200
JP CHENET X 750
JP CHENET LATA
Champaña Porttuse
GRAN BRINDIS 2600
PERTER LONGO  2500
"""),
    ("MALT", "Maltas, refajos y gaseosas", """
NATUMALTA 330*30
NATUMALTA 200 X 6
PET 330 X24
PONY 1.5 LTS X 6
PONY 2 LTS
PONY LATA X6
PONY LITRO X 15
PONY M-330 X 30
PONY MINI 200 x30
PONY MINI SIX GO
ZALVA X 12
BIG COLA 1.75
BIG COLA 400
BIG COLA 3 LTS
COCA 237
COCA ZERO 237
COCA ZERO 2.5 LT
COCA 350
COCA ZERO 1,375 X12
COCA ZERO 250
COCA ZERO 350
COCA COLA 600
COCA COLA LATA X 12 235
COCA COLA LATA X 12 330
COCA ZERO 400
COCA-COLA PET 250
COCACOLA 1,5 LTS X 12
COCACOLA 2 LITRO RET X9
COCACOLA 2,25 x 8
COCACOLA 3LTS X 6
COCACOLA 400
COCACOLA LITRO PET
COCACOLA LITRO RET
KOLA ROMAN 1.5
KOLA ROMAN 250 PET
KOLA ROMAN 400
QUATRO 1,5
QUATRO 2.5 *8
QUATRO 237
QUATRO 250 PET
QUATRO 3 LtS
QUATRO 350
QUATRO 400 PET
SCHWE PET 400 ml  SODA
SCHWEPPES 1,5 LTS GINGER X 12
SCHWEPPES 1,5 LTS SODA
SCHWEPPES AGUA TONICA
SCHWPET 400 ml  GINGER
SODA 350
SPRITE 1,5
SPRITE 237
SPRITE 3 LT
SPRITE 350
SPRITE 400 PET
BILACK
BRETAÑA 1.5 LTS x12
Bretaña 300ml x 24
BRETAÑA 350
CANADRY 1,5 X12
DUOS 3 LTS
ECONOLITRO x12
POST  250
POST 250 PET x 12
POST 350
POST 400 PET x15
POST 500 PET x15
POSTOBON 1,5
POSTOBON 1.25 Lts
Pepsi 2,5 LTS x8
POSTOBON 2,5 LTS x8
 POSTOBON 250 PET CERO X 12
POSTOBON 3 LITROS X 6
SQUASH
TROPICOLA  400ml x15
TROPICOLA 1,5 x12
TUTTI FRTY 400 X 15
TUTTI FRUTY 250
TUTTI FRUTY 1.5
"""),
    ("AJUG", "Aguas, jugos, hidratantes y tés", """
ELECTROLIT
HIDRALITE
AGUA PET POOL 300
AGUA PET POOL 600
AGUA PET POOL 600 gas
AGUA VIDA 7
AGUA VIDA LT
AGUA ZEND X 6
AMPER 473 X6
POOL 250
CIELO 620
CIELO 1 LT
CIFRUT 250
CIFRUT 400
PULP 400
NECTAR 300
SAVILOE 320X24
SAVILOE 420 X24
SPORADE 500
SPORADE 1.2
VIVE 100 BT 240X6
VIVE 100 BT 380X6
BOTELLON BRISA
BRISA * 24 600
BRISA 280
BRISA AGUA  SABORES 280
BRISA AGUA BIDON 6 Lts X2
BRISA LITRO X6
BRISA MANZANA 1.5 X 12
BRISA SABORES 600 X6
BRISA x24 600 con gas
FUZE TEA 400 X6
MANATIAL GAS x12
MANATIAL x12
MANATIAL x12 Vidrio
MOSTER LATA 473ml X 24
POWERADE X6 500ML
SOPORTE BOTELLON
VALLE 1.5 X 12
VALLE  250*12
VALLE FRESH 400 x 12
VALLE 2.5
MR TE 1.5
MR TE 300*12
ACQUA 400*15
ACQUA 250*12
CRISTAL 3.125
CRISTAL 250 X 12 GAS
CRISTAL GARRAFA 5 LT
CRISTAL 300*24
CRISTAL 6 LTS
CRISTAL 600 ml x 24
CRISTAL 600ML CON GAS X 24
CRISTAL ALOE 330 x12
CRISTAL BOTELLON
GATORADE  LITE
CRISTAL LITRO x 12
GATORADE x12
H20 1.5
H2O 250 x12
HATSU SODA
HATSU TE 250
HIT 1 lt pet
HIT 1,5
HIT 250
HIT 300
HIT 350
HIT 500
HIT TBK LT
HIT TETRA CAJA 200 X 24
MR TEA 250*30
MR TEA 500
NECTAR 300
RED BULL 250X4
soporte BOTELLON
SPEDD BOTELLA
SPEDD LATA 310
SPEED LITRO
SPEED  400
"""),
    ("RTD", "Bebidas listas para tomar con alcohol", """
VODKA SMIRNOFF ICE LATA 269ML
VODKA SMIRNOFF ICE X 275ML
LOS CUATES 473
LOS CUATES 269
COCTEL CALDAS 295
GINEBRA GORDON 250 LATA
PARIS ICE BLACK
PARIS  ICE ROSE
FOUR LOCKO 355
FOUR LOCKO 473
BRETAÑA LATA CON ALCOHOL
"""),
]

# Categorías oficiales (sin subcategorías) y a cuál va cada bloque de la lista.
PRINCIPALES = {
    "CERV": "Cervezas",
    "AGRN": "Aguardientes y rones",
    "DEST": "Destilados importados",
    "LIDV": "Licores dulces y vinos",
    "SINA": "Bebidas sin alcohol",
}
BLOQUE = {
    "CBOT": "CERV", "CLAT": "CERV",
    "AGUA": "AGRN", "RON": "AGRN", "RONS": "AGRN",
    "WHIS": "DEST", "VODK": "DEST", "TEQU": "DEST", "GINE": "DEST", "BRAN": "DEST",
    "CREM": "LIDV", "VINO": "LIDV", "CHAM": "LIDV",
    "MALT": "SINA", "AJUG": "SINA",
}
# Las bebidas listas con alcohol (RTD) no tienen categoría propia: cada una va con su licor base.
RTD_DESTINO = [
    ("SMIRNOFF ICE", "DEST"), ("LOS CUATES", "DEST"), ("GORDON", "DEST"),
    ("COCTEL CALDAS", "AGRN"),
    ("PARIS", "LIDV"), ("FOUR LOCKO", "LIDV"), ("BRETAÑA", "LIDV"),
]

# Solo en categorías de cerveza y bebidas: "x13", "*24", "X 30" al final = canasta de N.
CATEGORIAS_CON_EMPAQUE = {"CBOT", "CLAT", "MALT", "AJUG"}
EMPAQUE = re.compile(r"[xX*]\s*(\d{1,2})\s*$")
CATEGORIA_PARA_PRUEBAS = "SINA"  # donde queda el producto de prueba "cocacola" (tiene compras)


def _limpiar(linea):
    return re.sub(r"\s+", " ", linea).strip()


class Command(BaseCommand):
    help = (
        "Reemplaza el catálogo (categorías, productos y presentaciones) por la lista completa "
        "de la distribuidora: una línea = un producto."
    )

    def add_arguments(self, parser):
        parser.add_argument("--dry-run", action="store_true", help="No guarda nada.")

    @transaction.atomic
    def handle(self, *args, **options):
        # 1. Productos que ya tienen movimientos (compras, ventas, lotes…) no se borran.
        protegidos = set()
        for rel in Producto._meta.related_objects:
            if rel.related_model is PresentacionProducto:
                continue
            protegidos |= set(
                rel.related_model.objects.exclude(**{f"{rel.field.name}__isnull": True})
                .values_list(rel.field.name, flat=True)
            )

        borrados = Producto.objects.exclude(pk__in=protegidos).delete()[0]

        # 2. Categorías oficiales (planas, sin subcategoría)
        categorias = {}
        for codigo, nombre in PRINCIPALES.items():
            cat, _creada = Categoria.objects.get_or_create(codigo=codigo, defaults={"nombre": nombre})
            if cat.nombre != nombre or cat.subcategoria_id:
                cat.nombre, cat.subcategoria = nombre, None
                cat.save(update_fields=["nombre", "subcategoria"])
            categorias[codigo] = cat

        # 3. Los productos protegidos pasan a una categoría oficial y sobran las demás.
        destino = categorias[CATEGORIA_PARA_PRUEBAS]
        Producto.objects.filter(pk__in=protegidos).update(categoria=destino, descripcion=destino.nombre)
        sobrantes = Categoria.objects.exclude(codigo__in=list(PRINCIPALES)).delete()[0]

        # 4. Productos y presentaciones
        prods = pres = 0
        for bloque, _nombre_bloque, texto in CATALOGO:
            vistos = set()
            for linea in texto.strip().splitlines():
                nombre = _limpiar(linea)
                if not nombre or nombre.lower() in vistos:
                    continue
                vistos.add(nombre.lower())

                if bloque == "RTD":
                    cod_cat = next(c for clave, c in RTD_DESTINO if clave in nombre.upper())
                else:
                    cod_cat = BLOQUE[bloque]
                cat = categorias[cod_cat]

                producto, creado = Producto.objects.get_or_create(
                    nombre=nombre, categoria=cat, defaults={"descripcion": cat.nombre},
                )
                prods += creado

                m = EMPAQUE.search(nombre) if bloque in CATEGORIAS_CON_EMPAQUE else None
                cantidad = int(m.group(1)) if m else 1
                _, creada = PresentacionProducto.objects.get_or_create(
                    producto=producto,
                    defaults={
                        "nombre": f"Canasta x{cantidad}" if m else "Unidad",
                        "cantidad": cantidad,
                        "precio_venta": Decimal("0"),
                    },
                )
                pres += creada

        if options["dry_run"]:
            transaction.set_rollback(True)
            self.stdout.write(self.style.WARNING("DRY-RUN: no se guardó nada."))

        self.stdout.write(self.style.SUCCESS(
            f"Borrados (registros): {borrados}. Categorías sobrantes eliminadas: {sobrantes}. "
            f"Productos creados: {prods}. Presentaciones creadas: {pres}."
        ))
